const $=(selector)=>document.querySelector(selector);
const status=await send({type:"STATUS"}); renderStatus(status); await loadHistory();
document.querySelectorAll("[data-source]").forEach((button)=>button.addEventListener("click",()=>run(button.dataset.source)));
$("#settings").addEventListener("click",()=>chrome.runtime.openOptionsPage());
$("#upgrade").addEventListener("click",()=>chrome.runtime.openOptionsPage());

async function run(source){busy(true);toast("正在同步…");try{const result=await send({type:"RUN_SOURCE",source});if(!result.ok)throw new Error(result.error||`${result.failed} 条同步失败`);toast(`完成 · ${result.succeeded} 条内容`);await loadHistory();}catch(error){toast(error.message,true);}finally{busy(false)}}
function renderStatus(value){const license=$("#licenseStatus"),notion=$("#notionStatus"),active=!!value.access?.active,count=value.notionDatabaseCount||0;license.querySelector("span:last-child").textContent=value.access?.label||"未订阅";license.querySelector(".dot").classList.add(active?"ok":"warn");notion.querySelector("span:last-child").textContent=count?`Notion 已连接 ${count}/4`:"Notion 待设置";if(count)notion.querySelector(".dot").classList.add("ok");$("#paywallTitle").textContent=value.access?.mode==="expired"?"7 天完整试用已结束":"订阅验证暂不可用";$("#paywall").classList.toggle("hidden",active);document.querySelectorAll("[data-source]").forEach((button)=>button.disabled=!active||!value.notionSources?.[button.dataset.source])}
async function loadHistory(){const result=await send({type:"RECENT"});$("#history").innerHTML=result.items?.length?result.items.map((item)=>`<div class="history"><span>${label(item.source)} · ${item.succeeded} 条</span><span>${new Date(item.at).toLocaleDateString("zh-CN")}</span></div>`).join(""):"<div class=\"history\"><span>暂无记录</span></div>"}
function send(payload){return chrome.runtime.sendMessage(payload)}function busy(value){document.querySelectorAll("button").forEach((button)=>button.disabled=value)}function toast(value,error=false){$("#toast").textContent=value;$("#toast").classList.toggle("error",error)}function label(value){return({clip:"网页",weread:"微信读书",douban:"豆瓣",weibo:"微博"})[value]||value}
