const VERSION="2022-06-28";let nextAt=0;
export async function syncItems(token,databaseId,items){const results=[];for(const item of items){try{results.push({ok:true,id:await upsert(token,cleanId(databaseId),item)});}catch(error){results.push({ok:false,title:item.title,error:error.message});}}return results;}
async function upsert(token,databaseId,item){const externalId=String(item.externalId||item.url||item.title).slice(0,1900);const query=await notion(token,`/databases/${databaseId}/query`,{method:"POST",body:JSON.stringify({filter:{property:"外部 ID",rich_text:{equals:externalId}},page_size:1})});const properties=props(item,externalId);if(query.results?.[0]){await notion(token,`/pages/${query.results[0].id}`,{method:"PATCH",body:JSON.stringify({properties})});await replaceManaged(token,query.results[0].id,item);return query.results[0].id;}const page=await notion(token,"/pages",{method:"POST",body:JSON.stringify({parent:{database_id:databaseId},properties,children:[managed(item)]})});return page.id;}
async function replaceManaged(token,pageId,item){const children=await notion(token,`/blocks/${pageId}/children?page_size=100`),old=(children.results||[]).find(block=>block.type==="toggle"&&(block.toggle?.rich_text||[]).map(part=>part.plain_text||part.text?.content||"").join("")==="TunNest 自动同步区域");if(old)await notion(token,`/blocks/${old.id}`,{method:"DELETE"});await notion(token,`/blocks/${pageId}/children`,{method:"PATCH",body:JSON.stringify({children:[managed(item)]})});}
function managed(item){return{object:"block",type:"toggle",toggle:{rich_text:rich("TunNest 自动同步区域"),color:"gray_background",children:blocks(item).slice(0,100)}};}
function props(item,externalId){return{"标题":{title:rich(item.title,1900)},"类型":{select:{name:({book:"书籍",movie:"电影"})[item.kind]||item.kind}},"平台":{select:{name:item.source==="weread"?"微信读书":"豆瓣"}},"原文":{url:item.url||null},"作者":{rich_text:rich(item.author||"",1900)},"摘要":{rich_text:rich(item.excerpt||"",1900)},"标签":{multi_select:(item.tags||[]).slice(0,20).map(name=>({name:String(name).slice(0,100)}))},"采集时间":{date:{start:item.capturedAt||new Date().toISOString()}},"外部 ID":{rich_text:rich(externalId,1900)}};}
function blocks(item){const output=[];if(item.url)output.push({object:"block",type:"bookmark",bookmark:{url:item.url}});for(const highlight of(item.highlights||[]).slice(0,90)){const text=[highlight.chapter,highlight.text,highlight.note?`笔记：${highlight.note}`:""].filter(Boolean).join("\n");output.push({object:"block",type:"quote",quote:{rich_text:rich(text,1900),color:"yellow_background"}});}if(item.content)for(const part of split(item.content).slice(0,80))output.push({object:"block",type:"paragraph",paragraph:{rich_text:rich(part,1900)}});return output.slice(0,100);}
async function notion(token,path,init={}){const wait=Math.max(0,nextAt-Date.now());if(wait)await new Promise(resolve=>setTimeout(resolve,wait));nextAt=Date.now()+350;const response=await fetch(`https://api.notion.com/v1${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Notion-Version":VERSION,"Content-Type":"application/json",...(init.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||`Notion 请求失败 (${response.status})`);return data;}
function rich(value,max=2000){return value?[{type:"text",text:{content:String(value).slice(0,max)}}]:[]}function split(value){return String(value).split(/\n{2,}/).map(part=>part.trim()).filter(Boolean).flatMap(part=>part.match(/[\s\S]{1,1900}/g)||[])}function cleanId(value){const match=String(value||"").match(/[0-9a-f]{32}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i);if(!match)throw new Error("NOTION_DATABASE_ID 无效");return match[0]}
