/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: fe1cf86718d8eddcde6430a0137dd913)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	ALLOWED_ORIGIN: "*";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
